# Generated by Django 5.0.2 on 2024-02-27 19:25

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('coordinator_name', models.CharField(max_length=100, null=True)),
                ('academic_degree', models.CharField(max_length=100)),
                ('is_ead', models.BooleanField(default=False)),
                ('shift', models.CharField(choices=[('N', 'Noturno'), ('D', 'Diurno')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Equivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, null=True)),
                ('start_semester', models.CharField(max_length=6, null=True)),
                ('total_workload', models.PositiveIntegerField(null=True)),
                ('optional_workload', models.PositiveIntegerField(null=True)),
                ('mandatory_workload', models.PositiveIntegerField(null=True)),
                ('max_total_free_module', models.PositiveIntegerField(null=True)),
                ('max_period_workload', models.PositiveIntegerField(null=True)),
                ('min_period_workload', models.PositiveIntegerField(null=True)),
                ('flow', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('num_semester', models.SmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.department'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_option', to='course.coursecurriculum')),
                ('equivalence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='course.equivalence')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.PositiveSmallIntegerField(null=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('credit', models.SmallIntegerField()),
                ('equivalences', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('prerequisites', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('corequisites', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('offer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='course.department')),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisiteSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_set', to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite', to='course.prerequisiteset')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite', to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=7)),
                ('schedule', models.CharField(max_length=100)),
                ('students_qtd', models.CharField(max_length=3)),
                ('occupied', models.CharField(default='0', max_length=3)),
                ('place', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='course.subject')),
            ],
        ),
        migrations.AddField(
            model_name='equivalence',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_eq', to='course.subject'),
        ),
        migrations.AddField(
            model_name='equivalence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_eq', to='course.subject'),
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OBR', 'OBRIGATÓRIA'), ('OPT', 'OPTATIVA'), ('ML', 'MÓDULO LIVRE')], max_length=3)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subject', to='course.coursecurriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subject', to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CoRequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_co', to='course.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corequisite', to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='OfferTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_teachers', to='course.offer')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_teachers', to='course.teacher')),
            ],
        ),
    ]
