# Generated by Django 5.0.2 on 2024-02-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade_infos',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pass_percent',
        ),
        migrations.DeleteModel(
            name='SemesterGrade',
        ),
    ]
