# Generated by Django 5.0.2 on 2024-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sigaa_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
