# Generated by Django 5.0.2 on 2024-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumsubject',
            name='semester',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
