# Generated by Django 5.0.2 on 2024-02-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecurriculum',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
