# Generated by Django 5.0.2 on 2024-02-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_department_sigaa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sigaa_id',
        ),
    ]
